// allwinner,sun50i-h6-dw-hdmi

#ifndef HDMI_H
#define HDMI_H

#include "../util.h"

#define HDMI_BASE                               0x6000000

/* Identification Registers */
#define HDMI_DESIGN_ID                          (HDMI_BASE + 0x0000)
#define HDMI_REVISION_ID                        (HDMI_BASE + 0x0001)
#define HDMI_PRODUCT_ID0                        (HDMI_BASE + 0x0002)
#define HDMI_PRODUCT_ID1                        (HDMI_BASE + 0x0003)
#define HDMI_CONFIG2_ID                         (HDMI_BASE + 0x0006)

/* HDMI_3D_TX_PHY_CKCALCTRL values */
#define HDMI_3D_TX_PHY_CKCALCTRL_OVERRIDE       BIT(15)

/* HDMI_3D_TX_PHY_MSM_CTRL values */
#define HDMI_3D_TX_PHY_MSM_CTRL_CKO_SEL_FB_CLK  (3 << 1)

/*
 * HDMI 3D TX PHY registers
 */
#define HDMI_3D_TX_PHY_CKCALCTRL                0x05
#define HDMI_3D_TX_PHY_CPCE_CTRL                0x06
#define HDMI_3D_TX_PHY_CKSYMTXCTRL              0x09
#define HDMI_3D_TX_PHY_VLEVCTRL                 0x0e
#define HDMI_3D_TX_PHY_CURRCTRL                 0x10
#define HDMI_3D_TX_PHY_PLLPHBYCTRL              0x13
#define HDMI_3D_TX_PHY_GMPCTRL                  0x15
#define HDMI_3D_TX_PHY_MSM_CTRL                 0x17
#define HDMI_3D_TX_PHY_TXTERM                   0x19

/* Interrupt Registers */
#define HDMI_IH_I2CM_STAT0                      (HDMI_BASE + 0x0105)
#define HDMI_IH_I2CMPHY_STAT0                   (HDMI_BASE + 0x0108)
#define HDMI_IH_MUTE_FC_STAT0                   (HDMI_BASE + 0x0180)
#define HDMI_IH_MUTE_FC_STAT1                   (HDMI_BASE + 0x0181)
#define HDMI_IH_MUTE_FC_STAT2                   (HDMI_BASE + 0x0182)
#define HDMI_IH_MUTE_AS_STAT0                   (HDMI_BASE + 0x0183)
#define HDMI_IH_MUTE_PHY_STAT0                  (HDMI_BASE + 0x0184)
#define HDMI_IH_MUTE_I2CM_STAT0                 (HDMI_BASE + 0x0185)
#define HDMI_IH_MUTE_CEC_STAT0                  (HDMI_BASE + 0x0186)
#define HDMI_IH_MUTE_VP_STAT0                   (HDMI_BASE + 0x0187)
#define HDMI_IH_MUTE_I2CMPHY_STAT0              (HDMI_BASE + 0x0188)
#define HDMI_IH_MUTE_AHBDMAAUD_STAT0            (HDMI_BASE + 0x0189)
#define HDMI_IH_MUTE                            (HDMI_BASE + 0x01FF)

/* Video Sample Registers */
#define HDMI_TX_INVID0                          (HDMI_BASE + 0x0200)
#define HDMI_TX_INSTUFFING                      (HDMI_BASE + 0x0201)
#define HDMI_TX_GYDATA0                         (HDMI_BASE + 0x0202)
#define HDMI_TX_GYDATA1                         (HDMI_BASE + 0x0203)
#define HDMI_TX_RCRDATA0                        (HDMI_BASE + 0x0204)
#define HDMI_TX_RCRDATA1                        (HDMI_BASE + 0x0205)
#define HDMI_TX_BCBDATA0                        (HDMI_BASE + 0x0206)
#define HDMI_TX_BCBDATA1                        (HDMI_BASE + 0x0207)

/* Video Packetizer Registers */
#define HDMI_VP_PR_CD                           (HDMI_BASE + 0x0801)
#define HDMI_VP_STUFF                           (HDMI_BASE + 0x0802)
#define HDMI_VP_REMAP                           (HDMI_BASE + 0x0803)
#define HDMI_VP_CONF                            (HDMI_BASE + 0x0804)
#define HDMI_VP_MASK                            (HDMI_BASE + 0x0807)

/* Frame Composer Registers */
#define HDMI_FC_INVIDCONF                       (HDMI_BASE + 0x1000)
#define HDMI_FC_INHACTV0                        (HDMI_BASE + 0x1001)
#define HDMI_FC_INHACTV1                        (HDMI_BASE + 0x1002)
#define HDMI_FC_INHBLANK0                       (HDMI_BASE + 0x1003)
#define HDMI_FC_INHBLANK1                       (HDMI_BASE + 0x1004)
#define HDMI_FC_INVACTV0                        (HDMI_BASE + 0x1005)
#define HDMI_FC_INVACTV1                        (HDMI_BASE + 0x1006)
#define HDMI_FC_INVBLANK                        (HDMI_BASE + 0x1007)
#define HDMI_FC_HSYNCINDELAY0                   (HDMI_BASE + 0x1008)
#define HDMI_FC_HSYNCINDELAY1                   (HDMI_BASE + 0x1009)
#define HDMI_FC_HSYNCINWIDTH0                   (HDMI_BASE + 0x100A)
#define HDMI_FC_HSYNCINWIDTH1                   (HDMI_BASE + 0x100B)
#define HDMI_FC_VSYNCINDELAY                    (HDMI_BASE + 0x100C)
#define HDMI_FC_VSYNCINWIDTH                    (HDMI_BASE + 0x100D)
#define HDMI_FC_CTRLDUR                         (HDMI_BASE + 0x1011)
#define HDMI_FC_EXCTRLDUR                       (HDMI_BASE + 0x1012)
#define HDMI_FC_EXCTRLSPAC                      (HDMI_BASE + 0x1013)
#define HDMI_FC_CH0PREAM                        (HDMI_BASE + 0x1014)
#define HDMI_FC_CH1PREAM                        (HDMI_BASE + 0x1015)
#define HDMI_FC_CH2PREAM                        (HDMI_BASE + 0x1016)
#define HDMI_FC_DATAUTO3                        (HDMI_BASE + 0x10B7)
#define HDMI_FC_MASK0                           (HDMI_BASE + 0x10D2)
#define HDMI_FC_MASK1                           (HDMI_BASE + 0x10D6)
#define HDMI_FC_MASK2                           (HDMI_BASE + 0x10DA)

/* HDMI Source PHY Registers */
#define HDMI_PHY_CONF0                          (HDMI_BASE + 0x3000)
#define HDMI_PHY_TST0                           (HDMI_BASE + 0x3001)
#define HDMI_PHY_STAT0                          (HDMI_BASE + 0x3004)
#define HDMI_PHY_MASK0                          (HDMI_BASE + 0x3006)

/* HDMI Master PHY Registers */
#define HDMI_PHY_I2CM_SLAVE_ADDR                (HDMI_BASE + 0x3020)
#define HDMI_PHY_I2CM_ADDRESS_ADDR              (HDMI_BASE + 0x3021)
#define HDMI_PHY_I2CM_DATAO_1_ADDR              (HDMI_BASE + 0x3022)
#define HDMI_PHY_I2CM_DATAO_0_ADDR              (HDMI_BASE + 0x3023)
#define HDMI_PHY_I2CM_OPERATION_ADDR            (HDMI_BASE + 0x3026)
#define HDMI_PHY_I2CM_INT_ADDR                  (HDMI_BASE + 0x3027)
#define HDMI_PHY_I2CM_CTLINT_ADDR               (HDMI_BASE + 0x3028)

/* Audio Sampler Registers */
#define HDMI_AUD_INT                            (HDMI_BASE + 0x3102)
#define HDMI_AUD_SPDIFINT                       (HDMI_BASE + 0x3302)
#define HDMI_AUD_HBR_MASK                       (HDMI_BASE + 0x3404)

/*
 * Generic Parallel Audio Interface Registers
 * Not used as GPAUD interface is not enabled in hw
 */
#define HDMI_GP_MASK                            (HDMI_BASE + 0x3505)

/* Main Controller Registers */
#define HDMI_MC_CLKDIS                          (HDMI_BASE + 0x4001)
#define HDMI_MC_SWRSTZ                          (HDMI_BASE + 0x4002)
#define HDMI_MC_FLOWCTRL                        (HDMI_BASE + 0x4004)
#define HDMI_MC_PHYRSTZ                         (HDMI_BASE + 0x4005)
#define HDMI_MC_HEACPHY_RST                     (HDMI_BASE + 0x4007)

/* Color Space  Converter Registers */
#define HDMI_CSC_CFG                            (HDMI_BASE + 0x4100)
#define HDMI_CSC_SCALE                          (HDMI_BASE + 0x4101)

/* HDCP Encryption Engine Registers */
#define HDMI_A_HDCPCFG0                         (HDMI_BASE + 0x5000)
#define HDMI_A_HDCPCFG1                         (HDMI_BASE + 0x5001)
#define HDMI_A_APIINTMSK                        (HDMI_BASE + 0x5008)
#define HDMI_A_VIDPOLCFG                        (HDMI_BASE + 0x5009)

/* I2C Master Registers (E-DDC) */
#define HDMI_I2CM_SLAVE                         (HDMI_BASE + 0x7E00)
#define HDMI_I2CM_ADDRESS                       (HDMI_BASE + 0x7E01)
#define HDMI_I2CM_DATAI                         (HDMI_BASE + 0x7E03)
#define HDMI_I2CM_OPERATION                     (HDMI_BASE + 0x7E04)
#define HDMI_I2CM_INT                           (HDMI_BASE + 0x7E05)
#define HDMI_I2CM_CTLINT                        (HDMI_BASE + 0x7E06)
#define HDMI_I2CM_DIV                           (HDMI_BASE + 0x7E07)
#define HDMI_I2CM_SOFTRSTZ                      (HDMI_BASE + 0x7E09)

enum {
/* IH_I2CM_STAT0 and IH_MUTE_I2CM_STAT0 field values */
    HDMI_IH_I2CM_STAT0_DONE = 0x2,
    HDMI_IH_I2CM_STAT0_ERROR = 0x1,

/* IH_MUTE_FC_STAT2 field values */
    HDMI_IH_MUTE_FC_STAT2_OVERFLOW_MASK = 0x03,
    HDMI_IH_MUTE_FC_STAT2_LOW_PRIORITY_OVERFLOW = 0x02,
    HDMI_IH_MUTE_FC_STAT2_HIGH_PRIORITY_OVERFLOW = 0x01,

/* IH_MUTE field values */
    HDMI_IH_MUTE_MUTE_WAKEUP_INTERRUPT = 0x2,
    HDMI_IH_MUTE_MUTE_ALL_INTERRUPT = 0x1,

/* TX_INVID0 field values */
    HDMI_TX_INVID0_INTERNAL_DE_GENERATOR_MASK = 0x80,
    HDMI_TX_INVID0_INTERNAL_DE_GENERATOR_ENABLE = 0x80,
    HDMI_TX_INVID0_INTERNAL_DE_GENERATOR_DISABLE = 0x00,
    HDMI_TX_INVID0_VIDEO_MAPPING_MASK = 0x1F,
    HDMI_TX_INVID0_VIDEO_MAPPING_OFFSET = 0,

/* TX_INSTUFFING field values */
    HDMI_TX_INSTUFFING_BDBDATA_STUFFING_MASK = 0x4,
    HDMI_TX_INSTUFFING_BDBDATA_STUFFING_ENABLE = 0x4,
    HDMI_TX_INSTUFFING_BDBDATA_STUFFING_DISABLE = 0x0,
    HDMI_TX_INSTUFFING_RCRDATA_STUFFING_MASK = 0x2,
    HDMI_TX_INSTUFFING_RCRDATA_STUFFING_ENABLE = 0x2,
    HDMI_TX_INSTUFFING_RCRDATA_STUFFING_DISABLE = 0x0,
    HDMI_TX_INSTUFFING_GYDATA_STUFFING_MASK = 0x1,
    HDMI_TX_INSTUFFING_GYDATA_STUFFING_ENABLE = 0x1,
    HDMI_TX_INSTUFFING_GYDATA_STUFFING_DISABLE = 0x0,

/* VP_STUFF field values */
    HDMI_VP_STUFF_IDEFAULT_PHASE_MASK = 0x20,
    HDMI_VP_STUFF_IDEFAULT_PHASE_OFFSET = 5,
    HDMI_VP_STUFF_IFIX_PP_TO_LAST_MASK = 0x10,
    HDMI_VP_STUFF_IFIX_PP_TO_LAST_OFFSET = 4,
    HDMI_VP_STUFF_ICX_GOTO_P0_ST_MASK = 0x8,
    HDMI_VP_STUFF_ICX_GOTO_P0_ST_OFFSET = 3,
    HDMI_VP_STUFF_YCC422_STUFFING_MASK = 0x4,
    HDMI_VP_STUFF_YCC422_STUFFING_STUFFING_MODE = 0x4,
    HDMI_VP_STUFF_YCC422_STUFFING_DIRECT_MODE = 0x0,
    HDMI_VP_STUFF_PP_STUFFING_MASK = 0x2,
    HDMI_VP_STUFF_PP_STUFFING_STUFFING_MODE = 0x2,
    HDMI_VP_STUFF_PP_STUFFING_DIRECT_MODE = 0x0,
    HDMI_VP_STUFF_PR_STUFFING_MASK = 0x1,
    HDMI_VP_STUFF_PR_STUFFING_STUFFING_MODE = 0x1,
    HDMI_VP_STUFF_PR_STUFFING_DIRECT_MODE = 0x0,

/* VP_CONF field values */
    HDMI_VP_CONF_BYPASS_EN_MASK = 0x40,
    HDMI_VP_CONF_BYPASS_EN_ENABLE = 0x40,
    HDMI_VP_CONF_BYPASS_EN_DISABLE = 0x00,
    HDMI_VP_CONF_PP_EN_ENMASK = 0x20,
    HDMI_VP_CONF_PP_EN_ENABLE = 0x20,
    HDMI_VP_CONF_PP_EN_DISABLE = 0x00,
    HDMI_VP_CONF_PR_EN_MASK = 0x10,
    HDMI_VP_CONF_PR_EN_ENABLE = 0x10,
    HDMI_VP_CONF_PR_EN_DISABLE = 0x00,
    HDMI_VP_CONF_YCC422_EN_MASK = 0x8,
    HDMI_VP_CONF_YCC422_EN_ENABLE = 0x8,
    HDMI_VP_CONF_YCC422_EN_DISABLE = 0x0,
    HDMI_VP_CONF_BYPASS_SELECT_MASK = 0x4,
    HDMI_VP_CONF_BYPASS_SELECT_VID_PACKETIZER = 0x4,
    HDMI_VP_CONF_BYPASS_SELECT_PIX_REPEATER = 0x0,
    HDMI_VP_CONF_OUTPUT_SELECTOR_MASK = 0x3,
    HDMI_VP_CONF_OUTPUT_SELECTOR_BYPASS = 0x3,
    HDMI_VP_CONF_OUTPUT_SELECTOR_YCC422 = 0x1,
    HDMI_VP_CONF_OUTPUT_SELECTOR_PP = 0x0,

/* VP_REMAP field values */
    HDMI_VP_REMAP_MASK = 0x3,
    HDMI_VP_REMAP_YCC422_24bit = 0x2,
    HDMI_VP_REMAP_YCC422_20bit = 0x1,
    HDMI_VP_REMAP_YCC422_16bit = 0x0,

/* FC_DATAUTO3 field values */
    HDMI_FC_DATAUTO3_GCP_AUTO = 0x04,

/* PHY_CONF0 field values */
    HDMI_PHY_CONF0_PDZ_MASK = 0x80,
    HDMI_PHY_CONF0_PDZ_OFFSET = 7,
    HDMI_PHY_CONF0_ENTMDS_MASK = 0x40,
    HDMI_PHY_CONF0_ENTMDS_OFFSET = 6,
    HDMI_PHY_CONF0_SVSRET_MASK = 0x20,
    HDMI_PHY_CONF0_SVSRET_OFFSET = 5,
    HDMI_PHY_CONF0_GEN2_PDDQ_MASK = 0x10,
    HDMI_PHY_CONF0_GEN2_PDDQ_OFFSET = 4,
    HDMI_PHY_CONF0_GEN2_TXPWRON_MASK = 0x8,
    HDMI_PHY_CONF0_GEN2_TXPWRON_OFFSET = 3,
    HDMI_PHY_CONF0_GEN2_ENHPDRXSENSE_MASK = 0x4,
    HDMI_PHY_CONF0_GEN2_ENHPDRXSENSE_OFFSET = 2,
    HDMI_PHY_CONF0_SELDATAENPOL_MASK = 0x2,
    HDMI_PHY_CONF0_SELDATAENPOL_OFFSET = 1,
    HDMI_PHY_CONF0_SELDIPIF_MASK = 0x1,
    HDMI_PHY_CONF0_SELDIPIF_OFFSET = 0,

/* PHY_TST0 field values */
    HDMI_PHY_TST0_TSTCLR_MASK = 0x20,
    HDMI_PHY_TST0_TSTCLR_OFFSET = 5,
    HDMI_PHY_TST0_TSTEN_MASK = 0x10,
    HDMI_PHY_TST0_TSTEN_OFFSET = 4,
    HDMI_PHY_TST0_TSTCLK_MASK = 0x1,
    HDMI_PHY_TST0_TSTCLK_OFFSET = 0,

/* PHY_STAT0 field values */
    HDMI_PHY_RX_SENSE3 = 0x80,
    HDMI_PHY_RX_SENSE2 = 0x40,
    HDMI_PHY_RX_SENSE1 = 0x20,
    HDMI_PHY_RX_SENSE0 = 0x10,
    HDMI_PHY_HPD = 0x02,
    HDMI_PHY_TX_PHY_LOCK = 0x01,

/* PHY_I2CM_SLAVE_ADDR field values */
    HDMI_PHY_I2CM_SLAVE_ADDR_PHY_GEN2 = 0x69,
    HDMI_PHY_I2CM_SLAVE_ADDR_HEAC_PHY = 0x49,

/* PHY_I2CM_OPERATION_ADDR field values */
    HDMI_PHY_I2CM_OPERATION_ADDR_WRITE = 0x10,
    HDMI_PHY_I2CM_OPERATION_ADDR_READ = 0x1,

/* HDMI_PHY_I2CM_INT_ADDR */
    HDMI_PHY_I2CM_INT_ADDR_DONE_POL = 0x08,
    HDMI_PHY_I2CM_INT_ADDR_DONE_MASK = 0x04,

/* HDMI_PHY_I2CM_CTLINT_ADDR */
    HDMI_PHY_I2CM_CTLINT_ADDR_NAC_POL = 0x80,
    HDMI_PHY_I2CM_CTLINT_ADDR_NAC_MASK = 0x40,
    HDMI_PHY_I2CM_CTLINT_ADDR_ARBITRATION_POL = 0x08,
    HDMI_PHY_I2CM_CTLINT_ADDR_ARBITRATION_MASK = 0x04,

/* MC_CLKDIS field values */
    HDMI_MC_CLKDIS_HDCPCLK_DISABLE = 0x40,
    HDMI_MC_CLKDIS_CECCLK_DISABLE = 0x20,
    HDMI_MC_CLKDIS_CSCCLK_DISABLE = 0x10,
    HDMI_MC_CLKDIS_AUDCLK_DISABLE = 0x8,
    HDMI_MC_CLKDIS_PREPCLK_DISABLE = 0x4,
    HDMI_MC_CLKDIS_TMDSCLK_DISABLE = 0x2,
    HDMI_MC_CLKDIS_PIXELCLK_DISABLE = 0x1,

/* MC_SWRSTZ field values */
    HDMI_MC_SWRSTZ_I2SSWRST_REQ = 0x08,
    HDMI_MC_SWRSTZ_TMDSSWRST_REQ = 0x02,

/* MC_FLOWCTRL field values */
    HDMI_MC_FLOWCTRL_FEED_THROUGH_OFF_MASK = 0x1,
    HDMI_MC_FLOWCTRL_FEED_THROUGH_OFF_CSC_IN_PATH = 0x1,
    HDMI_MC_FLOWCTRL_FEED_THROUGH_OFF_CSC_BYPASS = 0x0,

/* MC_PHYRSTZ field values */
    HDMI_MC_PHYRSTZ_PHYRSTZ = 0x01,

/* MC_HEACPHY_RST field values */
    HDMI_MC_HEACPHY_RST_ASSERT = 0x1,
    HDMI_MC_HEACPHY_RST_DEASSERT = 0x0,

/* CSC_SCALE field values */
    HDMI_CSC_SCALE_CSC_COLORDE_PTH_MASK = 0xF0,
    HDMI_CSC_SCALE_CSC_COLORDE_PTH_24BPP = 0x00,
    HDMI_CSC_SCALE_CSC_COLORDE_PTH_30BPP = 0x50,
    HDMI_CSC_SCALE_CSC_COLORDE_PTH_36BPP = 0x60,
    HDMI_CSC_SCALE_CSC_COLORDE_PTH_48BPP = 0x70,
    HDMI_CSC_SCALE_CSCSCALE_MASK = 0x03,

/* A_HDCPCFG0 field values */
    HDMI_A_HDCPCFG0_ELVENA_MASK = 0x80,
    HDMI_A_HDCPCFG0_ELVENA_ENABLE = 0x80,
    HDMI_A_HDCPCFG0_ELVENA_DISABLE = 0x00,
    HDMI_A_HDCPCFG0_I2CFASTMODE_MASK = 0x40,
    HDMI_A_HDCPCFG0_I2CFASTMODE_ENABLE = 0x40,
    HDMI_A_HDCPCFG0_I2CFASTMODE_DISABLE = 0x00,
    HDMI_A_HDCPCFG0_BYPENCRYPTION_MASK = 0x20,
    HDMI_A_HDCPCFG0_BYPENCRYPTION_ENABLE = 0x20,
    HDMI_A_HDCPCFG0_BYPENCRYPTION_DISABLE = 0x00,
    HDMI_A_HDCPCFG0_SYNCRICHECK_MASK = 0x10,
    HDMI_A_HDCPCFG0_SYNCRICHECK_ENABLE = 0x10,
    HDMI_A_HDCPCFG0_SYNCRICHECK_DISABLE = 0x00,
    HDMI_A_HDCPCFG0_AVMUTE_MASK = 0x8,
    HDMI_A_HDCPCFG0_AVMUTE_ENABLE = 0x8,
    HDMI_A_HDCPCFG0_AVMUTE_DISABLE = 0x0,
    HDMI_A_HDCPCFG0_RXDETECT_MASK = 0x4,
    HDMI_A_HDCPCFG0_RXDETECT_ENABLE = 0x4,
    HDMI_A_HDCPCFG0_RXDETECT_DISABLE = 0x0,
    HDMI_A_HDCPCFG0_EN11FEATURE_MASK = 0x2,
    HDMI_A_HDCPCFG0_EN11FEATURE_ENABLE = 0x2,
    HDMI_A_HDCPCFG0_EN11FEATURE_DISABLE = 0x0,
    HDMI_A_HDCPCFG0_HDMIDVI_MASK = 0x1,
    HDMI_A_HDCPCFG0_HDMIDVI_HDMI = 0x1,
    HDMI_A_HDCPCFG0_HDMIDVI_DVI = 0x0,

/* A_HDCPCFG1 field values */
    HDMI_A_HDCPCFG1_DISSHA1CHECK_MASK = 0x8,
    HDMI_A_HDCPCFG1_DISSHA1CHECK_DISABLE = 0x8,
    HDMI_A_HDCPCFG1_DISSHA1CHECK_ENABLE = 0x0,
    HDMI_A_HDCPCFG1_PH2UPSHFTENC_MASK = 0x4,
    HDMI_A_HDCPCFG1_PH2UPSHFTENC_ENABLE = 0x4,
    HDMI_A_HDCPCFG1_PH2UPSHFTENC_DISABLE = 0x0,
    HDMI_A_HDCPCFG1_ENCRYPTIONDISABLE_MASK = 0x2,
    HDMI_A_HDCPCFG1_ENCRYPTIONDISABLE_DISABLE = 0x2,
    HDMI_A_HDCPCFG1_ENCRYPTIONDISABLE_ENABLE = 0x0,
    HDMI_A_HDCPCFG1_SWRESET_MASK = 0x1,
    HDMI_A_HDCPCFG1_SWRESET_ASSERT = 0x0,

/* A_VIDPOLCFG field values */
    HDMI_A_VIDPOLCFG_UNENCRYPTCONF_MASK = 0x60,
    HDMI_A_VIDPOLCFG_UNENCRYPTCONF_OFFSET = 5,
    HDMI_A_VIDPOLCFG_DATAENPOL_MASK = 0x10,
    HDMI_A_VIDPOLCFG_DATAENPOL_ACTIVE_HIGH = 0x10,
    HDMI_A_VIDPOLCFG_DATAENPOL_ACTIVE_LOW = 0x0,
    HDMI_A_VIDPOLCFG_VSYNCPOL_MASK = 0x8,
    HDMI_A_VIDPOLCFG_VSYNCPOL_ACTIVE_HIGH = 0x8,
    HDMI_A_VIDPOLCFG_VSYNCPOL_ACTIVE_LOW = 0x0,
    HDMI_A_VIDPOLCFG_HSYNCPOL_MASK = 0x2,
    HDMI_A_VIDPOLCFG_HSYNCPOL_ACTIVE_HIGH = 0x2,
    HDMI_A_VIDPOLCFG_HSYNCPOL_ACTIVE_LOW = 0x0,

/* I2CM_OPERATION field values */
    HDMI_I2CM_OPERATION_WRITE = 0x10,
    HDMI_I2CM_OPERATION_READ_EXT = 0x2,
    HDMI_I2CM_OPERATION_READ = 0x1,

/* I2CM_INT field values */
    HDMI_I2CM_INT_DONE_POL = 0x8,
    HDMI_I2CM_INT_DONE_MASK = 0x4,

/* I2CM_CTLINT field values */
    HDMI_I2CM_CTLINT_NAC_POL = 0x80,
    HDMI_I2CM_CTLINT_NAC_MASK = 0x40,
    HDMI_I2CM_CTLINT_ARB_POL = 0x8,
    HDMI_I2CM_CTLINT_ARB_MASK = 0x4,
};

#endif
